#ifndef MENU_H
#define MENU_H

void menu();

enum administrativeMenu
{
    LOGIN_AS_PATIENT_MANAGEMENT_USER = 1,
    LOGIN_AS_DOCTOR_MANAGEMENT_USER,
    LOGIN_AS_STAFF_MANAGEMENT_USER,
    LOGIN_AS_TREATMENT_AND_PRICE_MANAGEMENT_USER,
    LOGIN_AS_PHARMACY_MANAGEMENT_USER,
    LOGIN_AS_ROOM_MANAGEMENT_USER,
    EXIT_FROM_ADMINISTRATIVE_MENU
};

#endif // MENU_H

